# Secure Environment Variables for n8n-tweet Setup
# This file is automatically generated and will be securely deleted after use

# Domain Configuration
export DOMAIN="${domain}"
export N8N_SUBDOMAIN="${n8n_subdomain}"
export DASHBOARD_SUBDOMAIN="${dashboard_subdomain}"

# Database Configuration
export DB_PASSWORD="${db_password}"

# Redis Configuration  
export REDIS_PASSWORD="${redis_password}"

# Security Configuration
export ENCRYPTION_KEY="${encryption_key}"
export JWT_SECRET="${jwt_secret}"

# Additional Security Settings
export NODE_ENV="production"
export LOG_LEVEL="info"

# Mark all variables as sensitive to prevent logging
set +x